refactor: debugging workflow

diff --git a/.github/workflows/dagger.yml b/.github/workflows/dagger.yml
--- a/.github/workflows/dagger.yml
+++ b/.github/workflows/dagger.yml
@@ -1,10 +1,10 @@
 name: Run Dagger Pipeline
 
 on:
+  workflow_dispatch:
   push:
     branches:
-      - main
-      - workflow-fix
+      - dagger
 
 jobs:
   train:
@@ -29,6 +29,13 @@ jobs:
 
       - name: Run training pipeline
         run: dagger run go run ./pipeline.go
+
+      - name: Rename model
+        run: |
+          ls -al artifacts || true
+          test -f artifacts/lead_model_lr.pkl || (echo "Model not found: artifacts/lead_model_lr.pkl" && exit 1)
+          cp artifacts/lead_model_lr.pkl artifacts/model.pkl
+          ls -al artifacts
 
       - name: Upload Trained Model Artifact
         uses: actions/upload-artifact@v4
